#ifndef XMLCLASSESGLOBAL_H
#define XMLCLASSESGLOBAL_H

#if defined(XML_CLASSES_LIBRARY)
#define XML_CLASSES_EXPORT Q_DECL_EXPORT
#else
#define XML_CLASSES_EXPORT Q_DECL_IMPORT
#endif

#endif // XMLCLASSESGLOBAL_H
